QUESTIONS = [
    ("funding_confidence",
     "How would you describe your financial situation when it comes to paying for care?",
     ["Very confident", "Somewhat confident", "Not confident", "On Medicaid"],
     ["Very confident means cost won't limit choices.",
      "Somewhat confident means choices are possible with budgeting.",
      "Not confident means cost will strongly shape options.",
      "On Medicaid routes to Medicaid resources."]),

    ("cognition_level",
     "How would you rate your memory and thinking in daily life?",
     ["Sharp", "Sometimes forgetful", "Frequent memory issues", "Serious confusion"],
     ["We'll pair this with medications and safety to gauge supervision needs."]),

    ("adl_dependency",
     "How well can you manage everyday activities like bathing, dressing, or preparing meals on your own?",
     ["Independent", "Occasional reminders", "Help with some tasks", "Rely on help for most tasks"],
     ["ADLs include bathing, dressing, meals, and chores. This tells us the level of daily support."]),

    ("meds_complexity",
     "Do you take medications, and how manageable is the routine?",
     ["None", "A few, easy to manage", "Several, harder to manage", "Not sure"],
     ["This helps us understand missed‑med risk when combined with cognition."]),

    ("caregiver_support_level",
     "How much regular support do you have from a caregiver or family member?",
     ["I have support most of the time",
      "I have support a few days a week",
      "I have support occasionally",
      "I don’t have regular support"],
     ["Strong support can offset higher daily needs."]),

    ("mobility",
     "How do you usually get around?",
     ["I walk easily", "I use a cane", "I use a walker", "I use a wheelchair"],
     ["We mean typical movement at home and outside."]),

    ("social_isolation",
     "How often do you connect with friends, family, or activities?",
     ["Frequent contact", "Occasional contact", "Rarely see others", "Often alone"],
     None),

     ("geographic_access",
     "How accessible are services like pharmacies, grocery stores, and doctors from your home?",
     ["Very easy", "Fairly easy", "Somewhat difficult", "Very difficult"],
     ["Think drive time, transit availability, and how quickly you can get prescriptions or appointments."]),

    ("chronic_conditions",
     "Do you have any ongoing health conditions? Select all that apply.",
     ["Diabetes","Hypertension","Dementia","Parkinson's","Stroke","CHF","COPD","Arthritis"],
     ["Select all that apply. Dementia strongly influences recommendations."]),

    ("home_setup_safety",
     "How safe and manageable is your home for daily living as you age?",
     ["Well-prepared", "Mostly safe", "Needs modifications", "Not suitable"],
     ["Think stairs, bathrooms, lighting, grab bars, and trip hazards. We'll suggest an in‑home safety assessment if needed."]),

    ("recent_fall",
     "Has there been a fall in the last 6 months?",
     ["Yes","No","Not sure"],
     ["Recent falls increase the need for supervision or home changes."]),

    ("move_willingness",
     "If care is recommended, how open are you to changing where care happens?",
     ["I prefer to stay home",
      "I'd rather stay home but open if needed",
      "I'm comfortable either way",
      "I'm comfortable moving"],
     ["This helps us frame recommendations. It doesn't override safety."]),
]
